apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mais-de-100-projetos-Python
  annotations:
    github.com/project-slug: bpontes93/Mais-de-100-projetos-Python
spec:
  type: other
  lifecycle: unknown
  owner: guests
